version: '3'
services:
  coj-backend-gateway:
    container_name: coj-backend-gateway
    build: # 服务的 Docker 构建文件位置
      context: ./coj-backend-gateway
      dockerfile: Dockerfile
    ports:
    - "8101:8101"
    networks:
    - mynetwork

  coj-backend-user-service:
    container_name: coj-backend-user-service
    build:
      context: ./coj-backend-user-service
      dockerfile: Dockerfile
    ports:
    - "8102:8102"
    networks:
    - mynetwork
    depends_on: # 本服务依赖的服务，控制启动先后顺序
    - coj-backend-gateway

  coj-backend-question-service:
    container_name: coj-backend-question-service
    build:
      context: ./coj-backend-question-service
      dockerfile: Dockerfile
    ports:
    - "8103:8103"
    networks:
    - mynetwork
    depends_on:
    - coj-backend-user-service
    - coj-backend-gateway

  coj-backend-judge-service:
    container_name: coj-backend-judge-service
    build:
      context: ./coj-backend-judge-service
      dockerfile: Dockerfile
    ports:
    - "8104:8104"
    networks:
    - mynetwork
    depends_on:
    - coj-backend-user-service
    - coj-backend-question-service
    - coj-backend-gateway

# 网络，不定义的话就是默认网络
networks:
  mynetwork:
